# On déplace ici les configs du service Ebank
spring.application.name=ebank-service
server.port=8057
spring.datasource.url=jdbc:h2:mem:ebankdb
spring.h2.console.enabled=true
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
spring.cloud.compatibility-verifier.enabled=false

# 1. On donne un nom à l'instance (doit correspondre au name de l'annotation)
resilience4j.circuitbreaker.instances.customer-service.registerHealthIndicator=true

# 2. On définit la fenêtre d'analyse (regarde les 10 derniers appels)
resilience4j.circuitbreaker.instances.customer-service.slidingWindowSize=10

# 3. Si 50% de ces 10 appels échouent (soit 5 échecs), le circuit s'ouvre
resilience4j.circuitbreaker.instances.customer-service.failureRateThreshold=50

# 4. (Optionnel) Temps d'attente avant de réessayer d'appeler le service (ex: 5 secondes)
resilience4j.circuitbreaker.instances.customer-service.waitDurationInOpenState=5000
management.endpoints.web.exposure.include=health,circuitbreakers
management.endpoint.health.show-details=always


global.params.message=Bienvenue depuis le Config Server (Service Ebank) !

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7070/realms/ebank-realm
# Indispensable pour que le SecurityContext passe d'un thread à l'autre
resilience4j.circuitbreaker.instances.customer-service.thread-pool-key-override=true

# Si le config server est absent, on reessaie 10 fois avant de crash
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=10
spring.cloud.config.retry.initial-interval=2000
spring.cloud.config.retry.multiplier=1.5

#pour faciliter la connexion mixe au discovery (localhost or docker container)
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/


# MAIS on dit au service d aller chercher les cles de verification sur l URL interne Docker
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/ebank-realm/protocol/openid-connect/certs