# On déplace ici les configs du service Ebank
spring.application.name=ebank-service
server.port=8057
spring.datasource.url=jdbc:h2:mem:ebankdb
spring.h2.console.enabled=true
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
spring.cloud.compatibility-verifier.enabled=false

# 1. On donne un nom à l'instance (doit correspondre au name de l'annotation)
resilience4j.circuitbreaker.instances.customer-service.registerHealthIndicator=true

# 2. On définit la fenêtre d'analyse (regarde les 10 derniers appels)
resilience4j.circuitbreaker.instances.customer-service.slidingWindowSize=10

# 3. Si 50% de ces 10 appels échouent (soit 5 échecs), le circuit s'ouvre
resilience4j.circuitbreaker.instances.customer-service.failureRateThreshold=50

# 4. (Optionnel) Temps d'attente avant de réessayer d'appeler le service (ex: 5 secondes)
resilience4j.circuitbreaker.instances.customer-service.waitDurationInOpenState=5000
management.endpoints.web.exposure.include=health,circuitbreakers
management.endpoint.health.show-details=always


global.params.message=Bienvenue depuis le Config Server (Service Ebank) !