spring.application.name=gateway-service
server.port=9999
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
spring.cloud.compatibility-verifier.enabled=false
# URL du royaume Keycloak (Remplace localhost:7070 si tu as mis un autre port)
# Le nom du realm doit être EXACTEMENT celui cree dans Keycloak (ebank-realm)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7070/realms/ebank-realm

# 2. MAIS on donne l URL interne Docker pour que le service puisse telecharger les cles de signature
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/ebank-realm/protocol/openid-connect/certs

spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG

# Si le config server est absent, on reessaie 10 fois avant de crash
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=10
spring.cloud.config.retry.initial-interval=2000
spring.cloud.config.retry.multiplier=1.5

#pour faciliter la connexion mixe au discovery (localhost or docker container)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

