spring.application.name=gateway-service
server.port=9999
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
spring.cloud.compatibility-verifier.enabled=false
# URL du royaume Keycloak (Remplace localhost:7070 si tu as mis un autre port)
# Attention : Le nom du realm doit être EXACTEMENT celui créé dans Keycloak (ex: ebank-realm)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7070/realms/ebank-realm

# Autorise la Gateway à accéder aux informations du Token pour vérifier la signature
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:7070/realms/ebank-realm/protocol/openid-connect/certs

spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG