version: '3.8'

services:
  # 1. SERVEUR DE DÉCOUVERTE (EUREKA)
  discovery:
    build: ./discovery
    container_name: discovery
    ports:
      - "8761:8761"
    networks:
      - ebank-net

  # 2. SERVEUR DE CONFIGURATION
  config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/app/config-repo
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:/app/config-repo/
    # On attend que l'actuator réponde "UP" avant de considérer le service comme sain
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8888/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 15
    networks:
      - ebank-net

  # 3. SERVEUR D'IDENTITÉ (KEYCLOAK)
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "7070:7071"
    networks:
      - ebank-net

  # 4. API GATEWAY
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    restart: on-failure # Redémarre automatiquement si le Config Server n'est pas prêt
    ports:
      - "9999:9999"
    environment:
      - EUREKA_HOST=discovery
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/ebank-realm
    depends_on:
      config-service:
        condition: service_healthy # Attend le "OK" du Config Service
    networks:
      - ebank-net

  # 5. SERVICE CLIENT
  customer-service:
    build: ./customer-service
    container_name: customer-service
    restart: on-failure
    environment:
      - EUREKA_HOST=discovery
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/ebank-realm
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - ebank-net

  # 6. SERVICE BANQUE
  ebank-service:
    build: ./ebank-service
    container_name: ebank-service
    restart: on-failure
    environment:
      - EUREKA_HOST=discovery
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/ebank-realm
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - ebank-net

networks:
  ebank-net:
    driver: bridge