spring.application.name=discovery
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Desactive le mode d auto-preservation pour le developpement
eureka.server.enable-self-preservation=false
# Temps d attente avant de supprimer un service qui ne repond plus (optionnel)
eureka.server.eviction-interval-timer-in-ms=5000