
spring.application.name=config-service
server.port=8888

# 2. Utilisation du mode natif
spring.profiles.active=native

spring.cloud.config.server.native.search-locations=file://${user.home}/java/ebank-ms/config-repo
#pour actuator afin de verifie l'etat du service
management.endpoints.web.exposure.include=health